version: 3.1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: Dg2RuAuaLz+RP1kNxH6LqoEbVhsRIYI15lObO46PoTFYFwP87lXojzI91vdk+Km5
  skip_symbols: false
  artifact: 
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: tzUwO97cIRRZ9vgXaCaeV0ds46LzcowkJibAKrleVFE+a+OLG35YC9Kc5s5Mj7T0
  on:
    branch: master